<!--
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<link href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css" rel="stylesheet" type="text/css" />
<title>Google Maps JavaScript API v3 Example: Map Simple</title>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
  function initialize() {
    var myLatlng = new google.maps.LatLng(-34.397, 150.644);
    var myOptions = {
      zoom: 8,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
  }
</script>
</head>
<body onload="initialize()">
  <div id="map_canvas"></div>
</body>
</html>
-->
<?php foreach ($this->tweetsCollection as $tweet):?>
    <?php echo $tweet->getCreated()?><br />
    <?php echo $tweet->getFrom()?><br />
    <?php echo $tweet->getText()?><br />
    <?php if ($tweet->hasLocation()):?>
        <?php echo $tweet->getLocation()->getLatitude()?>
        x
        <?php echo $tweet->getLocation()->getLongitude()?>
    <?php endif;?>
    <hr>
<?php endforeach;?>

