<div><?php echo $this->form?></div>

<input type="hidden" name="map-center" id="map-center" value="<?php echo $this->map->getCenter()?>">
<input type="hidden" name="map-zoom" id="map-zoom" value="<?php echo $this->map->getZoom()?>">

<div id='layout'>
    <ul id='tweets'>
        <?php foreach ($this->tweets as $tweet):?>
        <li>
            <label><strong>@<?php echo $tweet->getFrom()?></strong></label> // <?php echo $tweet->getCreated()?>
            <p><?php echo $this->broker()->load('Application\\View\\Helper\\HighlightLink')->direct($tweet->getText())?></p>
            <?php if ($tweet->hasLocation()):?>
                <input type="hidden" value="<?php echo $tweet->getLocation()?>">
            <?php endif;?>
            <hr>
        </li>
        <?php endforeach;?>
    </ul>

    <div id='map'>
    </div>
</div>

