<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <link href="/styles/application.css" rel="stylesheet" type="text/css" />
    <title>Twee-Tag search</title>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script type="text/javascript" src="/scripts/application.js"></script>
</head>
<body>
<div>
<?php echo $this->form?>
</div>
<?php echo $this->broker('layout')->getLayout()->content; ?>
</body>
</html>

